[2022-12-12 13:07:49,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_Paper.get_song_task manual__2022-12-12T13:07:48.560093+00:00 [queued]>
[2022-12-12 13:07:49,189] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_Paper.get_song_task manual__2022-12-12T13:07:48.560093+00:00 [queued]>
[2022-12-12 13:07:49,190] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:07:49,191] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 13:07:49,191] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:07:49,201] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_song_task> on 2022-12-12 13:07:48.560093+00:00
[2022-12-12 13:07:49,206] {standard_task_runner.py:52} INFO - Started process 1044 to run task
[2022-12-12 13:07:49,211] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_Paper', 'get_song_task', 'manual__2022-12-12T13:07:48.560093+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpx6y1up1u', '--error-file', '/tmp/tmpv2c3sr0p']
[2022-12-12 13:07:49,212] {standard_task_runner.py:80} INFO - Job 45: Subtask get_song_task
[2022-12-12 13:07:49,292] {task_command.py:369} INFO - Running <TaskInstance: daily_Paper.get_song_task manual__2022-12-12T13:07:48.560093+00:00 [running]> on host cbcd6542cb8e
[2022-12-12 13:07:49,373] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_Paper
AIRFLOW_CTX_TASK_ID=get_song_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T13:07:48.560093+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T13:07:48.560093+00:00
[2022-12-12 13:07:49,382] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/song.py", line 7, in get_song
    res = requests.get('https://api.genius.com/songs/' + song_id,
TypeError: can only concatenate str (not "int") to str
[2022-12-12 13:07:49,394] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_Paper, task_id=get_song_task, execution_date=20221212T130748, start_date=20221212T130749, end_date=20221212T130749
[2022-12-12 13:07:49,407] {standard_task_runner.py:97} ERROR - Failed to execute job 45 for task get_song_task (can only concatenate str (not "int") to str; 1044)
[2022-12-12 13:07:49,423] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 13:07:49,453] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
