[2022-12-12 16:26:02,857] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:25:59.735310+00:00 [queued]>
[2022-12-12 16:26:02,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:25:59.735310+00:00 [queued]>
[2022-12-12 16:26:02,863] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:26:02,863] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 16:26:02,864] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:26:02,870] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 16:25:59.735310+00:00
[2022-12-12 16:26:02,873] {standard_task_runner.py:52} INFO - Started process 2925 to run task
[2022-12-12 16:26:02,876] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T16:25:59.735310+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpdbgegzwu', '--error-file', '/tmp/tmpkbp_uss0']
[2022-12-12 16:26:02,878] {standard_task_runner.py:80} INFO - Job 134: Subtask create_pdf_task
[2022-12-12 16:26:02,917] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:25:59.735310+00:00 [running]> on host cbcd6542cb8e
[2022-12-12 16:26:02,961] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T16:25:59.735310+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T16:25:59.735310+00:00
[2022-12-12 16:26:02,962] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 26, in create_pdf
    pdf.set_font('Monospace', 'C', 12)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 603, in set_font
    self.error('Undefined font: '+family+' '+style)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 227, in error
    raise RuntimeError('FPDF error: '+msg)
RuntimeError: FPDF error: Undefined font: monospace C
[2022-12-12 16:26:02,971] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T162559, start_date=20221212T162602, end_date=20221212T162602
[2022-12-12 16:26:02,976] {standard_task_runner.py:97} ERROR - Failed to execute job 134 for task create_pdf_task (FPDF error: Undefined font: monospace C; 2925)
[2022-12-12 16:26:03,008] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 16:26:03,030] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
