[2022-12-12 18:30:51,511] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T18:29:46.533674+00:00 [queued]>
[2022-12-12 18:30:51,516] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T18:29:46.533674+00:00 [queued]>
[2022-12-12 18:30:51,517] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:30:51,517] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-12 18:30:51,518] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:30:51,525] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 18:29:46.533674+00:00
[2022-12-12 18:30:51,529] {standard_task_runner.py:52} INFO - Started process 2485 to run task
[2022-12-12 18:30:51,532] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T18:29:46.533674+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpqdafeway', '--error-file', '/tmp/tmp1sg_7dci']
[2022-12-12 18:30:51,534] {standard_task_runner.py:80} INFO - Job 382: Subtask create_pdf_task
[2022-12-12 18:30:51,580] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T18:29:46.533674+00:00 [running]> on host 6bb81baa0a52
[2022-12-12 18:30:51,633] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T18:29:46.533674+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T18:29:46.533674+00:00
[2022-12-12 18:30:51,645] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 1716, in _parsejpg
    f = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './logo.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 60, in create_pdf
    pdf.image(logo, x = 50, y = 50, w = 50, h = 50)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 969, in image
    info=self._parsejpg(name)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 1738, in _parsejpg
    self.error('Missing or incorrect image file: %s. error: %s' % (filename, str(exception())))
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 227, in error
    raise RuntimeError('FPDF error: '+msg)
RuntimeError: FPDF error: Missing or incorrect image file: ./logo.jpg. error: [Errno 2] No such file or directory: './logo.jpg'
[2022-12-12 18:30:51,654] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T182946, start_date=20221212T183051, end_date=20221212T183051
[2022-12-12 18:30:51,660] {standard_task_runner.py:97} ERROR - Failed to execute job 382 for task create_pdf_task (FPDF error: Missing or incorrect image file: ./logo.jpg. error: [Errno 2] No such file or directory: './logo.jpg'; 2485)
[2022-12-12 18:30:51,705] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 18:30:51,728] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
