[2022-12-12 16:26:35,886] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:26:31.532092+00:00 [queued]>
[2022-12-12 16:26:35,891] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:26:31.532092+00:00 [queued]>
[2022-12-12 16:26:35,891] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:26:35,892] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 16:26:35,892] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:26:35,899] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 16:26:31.532092+00:00
[2022-12-12 16:26:35,902] {standard_task_runner.py:52} INFO - Started process 2942 to run task
[2022-12-12 16:26:35,905] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T16:26:31.532092+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpl939yxmm', '--error-file', '/tmp/tmp0owf3aay']
[2022-12-12 16:26:35,906] {standard_task_runner.py:80} INFO - Job 140: Subtask create_pdf_task
[2022-12-12 16:26:35,946] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:26:31.532092+00:00 [running]> on host cbcd6542cb8e
[2022-12-12 16:26:35,991] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T16:26:31.532092+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T16:26:31.532092+00:00
[2022-12-12 16:26:35,992] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 26, in create_pdf
    pdf.set_font('Times', 'C', 12)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 603, in set_font
    self.error('Undefined font: '+family+' '+style)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 227, in error
    raise RuntimeError('FPDF error: '+msg)
RuntimeError: FPDF error: Undefined font: times C
[2022-12-12 16:26:36,002] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T162631, start_date=20221212T162635, end_date=20221212T162636
[2022-12-12 16:26:36,007] {standard_task_runner.py:97} ERROR - Failed to execute job 140 for task create_pdf_task (FPDF error: Undefined font: times C; 2942)
[2022-12-12 16:26:36,037] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 16:26:36,059] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
